image: elixir:1.13
build:
  stage: build
  variables:
    MIX_ENV: test
  only:
    changes:
      - native/**
      - lib/**
      - test/**
      - '*.exs'
      - mix.lock
      - .gitlab-ci.yml
  script:
    - apt update -q -y
    - apt install -y git ca-certificates curl
    - curl https://sh.rustup.rs -sSf | sh -s -- -y
    - export PATH="$HOME/.cargo/bin:${PATH}"
    - mix local.hex --force
    - mix local.rebar --force
    - mix deps.get
    - mix test

