[package]
name = "image_rs_nif"
version = "0.1.0"
authors = []
edition = "2018"

[lib]
name = "image_rs_nif"
path = "src/lib.rs"
crate-type = ["cdylib"]

[dependencies]
rustler = "0.23.0"
image = "0"
