name: linux

on:
  pull_request:
  push:
    branches:
      - main
      - dev
    paths-ignore:
      - '**/README.md'
      - '.github/workflows/macos*'
      - '.github/workflows/nerves*'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-22.04
    env:
      MIX_ENV: test
      IMAGE_RS_BUILD: "true"

    steps:
      - uses: actions/checkout@v4

      - uses: erlef/setup-beam@v1
        with:
          otp-version: "26.2"
          elixir-version: "1.16"

      - name: Install system dependecies
        run: sudo apt-get update && sudo apt-get install -y build-essential automake autoconf pkg-config bc m4 curl git libssl-dev libncurses5-dev ca-certificates

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Compile and Test
        run: |
          mix deps.get
          mix deps.compile
          mix compile
          mix test
