name: macos

on:
  pull_request:
  push:
    branches:
      - main
      - dev
    paths-ignore:
      - '**/README.md'
      - '.github/workflows/linux*'
      - '.github/workflows/nerves*'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  mix_test:
    runs-on: macos-13
    env:
      MIX_ENV: test
      ELIXIR_VERSION: "1.16.0"
      IMAGE_RS_BUILD: "true"
    strategy:
      matrix:
        otp_version: ["25.3.2.8", "26.2.2"]

    name: macOS x86_64 - OTP ${{ matrix.otp_version }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download OTP
        run: |
          curl -fsSO https://elixir-lang.org/install.sh
          sh install.sh "elixir@${{ env.ELIXIR_VERSION }}" "otp@${{ matrix.otp_version }}"

      - name: Install Mix and Rebar
        run: |
          export OTP_VERSION=${{ matrix.otp_version }}
          export OTP_MAIN_VER="${OTP_VERSION%%.*}"
          export PATH=$HOME/.elixir-install/installs/otp/${{ matrix.otp_version }}/bin:$PATH
          export PATH=$HOME/.elixir-install/installs/elixir/${{ env.ELIXIR_VERSION }}-otp-${OTP_MAIN_VER}/bin:$PATH
          mix local.hex --force
          mix local.rebar --force

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Compile and Test
        run: |
          export OTP_VERSION=${{ matrix.otp_version }}
          export OTP_MAIN_VER="${OTP_VERSION%%.*}"
          export PATH=$HOME/.elixir-install/installs/otp/${{ matrix.otp_version }}/bin:$PATH
          export PATH=$HOME/.elixir-install/installs/elixir/${{ env.ELIXIR_VERSION }}-otp-${OTP_MAIN_VER}/bin:$PATH

          mix deps.get
          mix deps.compile
          mix compile
          mix test
